server:
  port: 8080
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: MServiceFramework

feign:
  client:
    config:
      default:
        connectTimeout: 80000000
        readTimeout: 80000000